# Copyright (C) 2018-2025 VyOS maintainers and contributors
# Copyright (C) 2026 Perle Systems Limited (iGOS modifications)
#
# This program is free software; you can redistribute it and/or modify
# in order to easy exprort images built to "external" world
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Must be run with --privileged flag, recommended to run the container with a
# volume mapped in order to easy export images

# This Dockerfile is installable on both x86, x86-64, armhf and arm64 systems
ARG ARCH=
FROM ${ARCH}debian:bookworm-slim


RUN grep "VERSION_ID" /etc/os-release || (echo 'VERSION_ID="12"' >> /etc/os-release)

# It is also possible to emulate an arm system inside docker,
# execution of this emulated system needs to be executed on an x86 or x86-64 host.

# To install using a non-native cpu instructionset use the `--build-arg ARCH=<ARCH>/`
# Supported architectures:
#     arm64v8/
# Example bo byukd natively:
#     docker build -t vyos-build:current .
# Example to build on arm64:
#     docker build -t vyos-build:current-arm64 --build-arg ARCH=arm64v8/ .

# On some versions of docker the emulation framework is not installed by default and
# you need to install qemu, qemu-user-static and register qemu inside docker manually using:
# `docker run --rm --privileged multiarch/qemu-user-static:register --reset`
LABEL authors="Perle Systems Limited <psleng@perle.com>" \
      org.opencontainers.image.authors="Perle Systems Limited <psleng@perle.com>" \
      org.opencontainers.image.url="https://github.com/psleng/vyos-build" \
      org.opencontainers.image.documentation="https://github.com/psleng/vyos-build#readme" \
      org.opencontainers.image.source="https://github.com/psleng/vyos-build" \
      org.opencontainers.image.vendor="Perle Systems Limited" \
      org.opencontainers.image.licenses="GPL-2.0-or-later" \
      org.opencontainers.image.title="igos-build" \
      org.opencontainers.image.description="Container to build iGOS images (derived from VyOS build tooling)" \
      org.opencontainers.image.base.name="docker.io/debian/debian:bookworm" \
      org.opencontainers.image.upstream="VyOS" \
      org.opencontainers.image.upstream.source="https://github.com/vyos/vyos-build"
ENV DEBIAN_FRONTEND=noninteractive

RUN /bin/echo -e 'APT::Install-Recommends "0";\nAPT::Install-Suggests "0";' > /etc/apt/apt.conf.d/01norecommends
# Clean cache after each apt-get install command so that it is not stored in the image
RUN /bin/echo -e 'DPkg::Post-Invoke {"/bin/rm -f /var/cache/apt/archives/*.deb /var/lib/apt/lists/* || true";};' > /etc/apt/apt.conf.d/clean

RUN apt-get update && apt-get install -y \
      dialog \
      apt-utils \
      locales

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen
ENV LANG=en_US.utf8

ENV OCAML_VERSION=4.14.2

# Base packaged needed to build packages and their package dependencies
RUN apt-get update && apt-get install -y \
      bash \
      bash-completion \
      vim \
      vim-autopep8 \
      nano \
      git \
      curl \
      sudo \
      mc \
      pbuilder \
      devscripts \
      equivs \
      lsb-release \
      libtool \
      libapt-pkg-dev \
      flake8 \
      pkg-config \
      debhelper \
      gosu \
      po4a \
      openssh-client \
      jq \
      less \
      socat \
      python-is-python3 \
      apt-transport-https

# Packages needed for vyos-build
RUN apt-get update && apt-get install -y \
      build-essential \
      python3-pystache \
      squashfs-tools \
      genisoimage \
      fakechroot \
      pipx \
      python3-git \
      python3-pip \
      python3-flake8 \
      python3-autopep8 \
      python3-tomli \
      python3-tomli-w \
      yq \
      debootstrap \
      live-build \
      gdisk \
      sbsigntool \
      dosfstools \
      kpartx \
      npm \
      nodejs

# Packages for TPM test
RUN apt-get update && apt-get install -y swtpm

# Syslinux and Grub2 is only supported on x86 and x64 systems
RUN if dpkg-architecture -ii386 || dpkg-architecture -iamd64; then \
      apt-get update && apt-get install -y \
        syslinux \
        grub2; \
    fi

# Building libvyosconf requires a full configured OPAM/OCaml setup
RUN apt-get update && apt-get install -y \
      quilt \
      debhelper \
      libffi-dev \
      libpcre2-dev \
      unzip

# Update certificate store to not crash ocaml package install
# Apply fix for https in curl running on armhf
RUN dpkg-reconfigure ca-certificates; \
    if dpkg-architecture -iarmhf; then \
      echo "cacert=/etc/ssl/certs/ca-certificates.crt" >> ~/.curlrc; \
    fi

# Installing OCaml needed to compile libvyosconfig
RUN curl https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh \
      --output /tmp/opam_install.sh --retry 10 --retry-delay 5 && \
    sed -i 's/read_tty BINDIR/BINDIR=""/' /tmp/opam_install.sh && sh /tmp/opam_install.sh && \
    opam init --root=/opt/opam --comp=${OCAML_VERSION} --disable-sandboxing --no-setup \
    && rm /tmp/opam_install.sh

RUN eval $(opam env --root=/opt/opam --set-root) && opam install -y \
      re \
      pcre2 \
      num \
      ctypes \
      ctypes-foreign \
      ctypes-build \
      containers \
      fileutils \
      xml-light \
      mustache \
      yojson \
      fmt \
      logs

# Packages needed for open-vmdk
RUN apt-get update && apt-get install -y \
      zlib1g-dev

# Install open-vmdk
RUN wget -O /tmp/open-vmdk-master.zip https://github.com/vmware/open-vmdk/archive/master.zip && \
    unzip -d /tmp/ /tmp/open-vmdk-master.zip && \
    cd /tmp/open-vmdk-master/ && make && make install && \
    cd /tmp && rm -rf /tmp/open-vmdk-master/ && rm /tmp/open-vmdk-master.zip

# Packages need for build live-build
RUN apt-get update && apt-get install -y \
      cpio

COPY patches/live-build/0001-save-package-info.patch /tmp/0001-save-package-info.patch

RUN git clone https://salsa.debian.org/live-team/live-build.git /tmp/live-build && \
    cd /tmp/live-build && git checkout debian/1%20240810 && \
    patch -p1 < /tmp/0001-save-package-info.patch && \
    dch -n "Applying fix for save package info" && \
    dpkg-buildpackage -us -uc && \
    dpkg -i ../live-build*.deb && \
    rm -rf /tmp/live-build

#
# live-build: building in docker fails with mounting /proc | /sys
#
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919659
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921815
# https://salsa.debian.org/installer-team/debootstrap/merge_requests/26
#
RUN wget https://salsa.debian.org/klausenbusk-guest/debootstrap/commit/a9a603b17cadbf52cb98cde0843dc9f23a08b0da.patch \
      -O /tmp/a9a603b17cadbf52cb98cde0843dc9f23a08b0da.patch && \
    git clone https://salsa.debian.org/installer-team/debootstrap /tmp/debootstrap && \
    cd /tmp/debootstrap && git checkout 1.0.114 && \
    patch -p1 < /tmp/a9a603b17cadbf52cb98cde0843dc9f23a08b0da.patch && \
    dch -n "Applying fix for docker image compile" && \
    dpkg-buildpackage -us -uc && \
    sudo dpkg -i ../debootstrap*.deb \
    && rm /tmp/a9a603b17cadbf52cb98cde0843dc9f23a08b0da.patch \
    && rm -rf /tmp/debootstrap

# Packages needed for Linux Kernel
# cmake required by accel-ppp
RUN apt-get update && apt-get install -y \
      cmake \
      gnupg2 \
      rsync \
      libelf-dev \
      libncurses5-dev \
      flex \
      bison \
      bc \
      kmod \
      cpio \
      python-is-python3 \
      dwarves \
      nasm \
      rdfind

# Packages needed for Intel QAT out-of-tree drivers
# FPM is used when generation Debian pckages for e.g. Intel QAT drivers
RUN apt-get update && apt-get install -y \
      pciutils \
      yasm \
      ruby \
      libudev-dev \
      ruby-dev \
      rubygems \
      build-essential
RUN gem install --no-document fpm

# Add psleng package repo
# PSL: Install apt pubkey and sources.list.d file for psleng.github.io
RUN echo "deb [signed-by=/etc/apt/keyrings/psleng.key] https://psleng.github.io current main" >> /etc/apt/sources.list.d/psleng.list
COPY psleng.key /etc/apt/keyrings/

# Packages needed for vyos-1x
RUN pip --no-cache --no-cache-dir install --break-system-packages \
      git+https://github.com/aristanetworks/j2lint.git@341b5d5db86 \
      pyhumps==3.8.0; \
    apt-get update && apt-get install -y \
      build-essential \
      dh-python \
      fakeroot \
      iproute2 \
      libzmq3-dev \
      procps \
      protobuf-compiler \
      python3 \
      python3-setuptools \
      python3-inotify \
      python3-xmltodict \
      python3-lxml \
      python3-nose2 \
      python3-netifaces \
      python3-jinja2 \
      python3-jmespath \
      python3-psutil \
      python3-stdeb \
      python3-all \
      python3-coverage \
      python3-hurry.filesize \
      python3-netaddr \
      python3-paramiko \
      python3-passlib \
      python3-protobuf \
      python3-tabulate \
      python3-zmq \
      python3-vici \
      python3-fastapi \
      python3-pyudev \
      python3-systemd \
      python3-certbot-nginx \
      python3-pam \
      python3-dbus \
      python3-pyroute2 \
      python3-voluptuous \
      pylint \
      quilt \
      whois \
      python3-cracklib

# Go required for telegraf and prometheus exporters build
RUN GO_VERSION_INSTALL="1.23.2" ; \
    if [ "$ARCH" = "arm64v8" ]; then \
        wget -O /tmp/go${GO_VERSION_INSTALL}.linux-arm64.tar.gz https://go.dev/dl/go${GO_VERSION_INSTALL}.linux-$(dpkg-architecture -qDEB_HOST_ARCH).tar.gz ; \
    else \
        wget -O /tmp/go${GO_VERSION_INSTALL}.linux-amd64.tar.gz https://go.dev/dl/go${GO_VERSION_INSTALL}.linux-$(dpkg-architecture -qDEB_HOST_ARCH).tar.gz ; \
    fi && \
    tar -C /opt -xzf /tmp/go*.tar.gz && \
    rm /tmp/go*.tar.gz
RUN echo "export PATH=/opt/go/bin:$PATH" >> /etc/bash.bashrc

# Packages needed for Qemu test-suite
# Packages for i386 and amd64 platforms
RUN if dpkg-architecture -ii386 || dpkg-architecture -iamd64; then \
      apt-get update && apt-get install -y \
        python3-pexpect \
        ovmf \
        qemu-system-x86 \
        qemu-utils \
        qemu-kvm; \
    fi

# Packages for arm64 platform
RUN if dpkg-architecture -iarm64; then \
      apt-get update && apt-get install -y \
        python3-pexpect \
        ipxe-qemu \
        qemu-system-aarch64 \
        qemu-efi-aarch64; \
    fi

# Packages needed for building vmware and GCE images
# This is only supported on i386 and amd64 platforms
RUN if dpkg-architecture -ii386 || dpkg-architecture -iamd64; then \
     apt-get update && apt-get install -y \
      parted \
      udev \
      grub-pc \
      grub2-common; \
    fi

# Packages needed for vyos-cloud-init
RUN apt-get update && apt-get install -y \
      python3-configobj \
      python3-httpretty \
      python3-jsonpatch \
      python3-mock \
      python3-oauthlib \
      python3-pep8 \
      python3-pyflakes \
      python3-serial \
      python3-unittest2 \
      python3-yaml \
      python3-jsonschema \
      python3-contextlib2 \
      python3-pytest-cov \
      cloud-utils

# Install utilities for building grub and u-boot images
RUN if dpkg-architecture -iarm64; then \
    apt-get update && apt-get install -y \
      dosfstools \
      u-boot-tools \
      grub-efi-$(dpkg-architecture -qDEB_HOST_ARCH); \
    elif dpkg-architecture -iarmhf; then \
    apt-get update && apt-get install -y \
      dosfstools \
      u-boot-tools \
      grub-efi-arm; \
    fi

# Packages needed for openvpn-otp
RUN apt-get update && apt-get install -y \
      debhelper \
      libssl-dev \
      openvpn

# Packages needed for OWAMP/TWAMP (service sla)
RUN git clone -b 4.4.6 https://github.com/perfsonar/i2util.git /tmp/i2util && \
      cd /tmp/i2util && \
      dpkg-buildpackage -uc -us -tc -b && \
      dpkg -i /tmp/*i2util*_$(dpkg-architecture -qDEB_HOST_ARCH).deb

# Package needed for building Kea
RUN echo "deb http://deb.debian.org/debian bookworm-backports main" \
      > /etc/apt/sources.list.d/bookworm-backports.list \
      && apt-get update \
      && apt install -y -t bookworm-backports meson

# Creating image for embedded systems needs this utilities to prepare a image file
RUN apt-get update && apt-get install -y \
      parted \
      udev \
      zip

# Packages needed for Accel-PPP
# XXX: please note that this must be installed after nftable dependencies - otherwise
# APT will remove liblua5.3-dev which breaks the Accel-PPP build
# With bookworm, updated to libssl3 (Note: https://github.com/accel-ppp/accel-ppp/issues/68)
RUN apt-get update && apt-get install -y \
      liblua5.3-dev \
      libssl3 \
      libssl-dev

# debmake: a native Debian tool for preparing sources for packaging
RUN apt-get update && apt-get install -y \
      debmake \
      python3-debian

# Packages for jool
RUN apt-get update && apt-get install -y \
      libnl-genl-3-dev \
      libxtables-dev

# PSL: Packages needed for OWAMP - JF
RUN apt-get update && apt-get install -y \
	dh-apparmor \
	dh-exec \
	libcap-dev

# PSL: Packages needed for Strongswan - JF
RUN apt-get update && apt-get install -y \
	bison \
	bzip2 \
	debhelper-compat \
	dh-apparmor \
	dpkg-dev  \
	flex \
	gperf \
	libiptc-dev \
	libcap-dev \
	libcurl3-dev \
	libgcrypt20-dev \
	libgmp3-dev \
	libkrb5-dev \
	libldap2-dev \
	libnm-dev \
	libpam0g-dev \
	libsqlite3-dev \
	libssl-dev \
	libtool \
	libtss2-dev \
	libxml2-dev \
	pkg-config \
	po-debconf \
	systemd \
	tzdata \
	libcurl4-openssl-dev \
	libgmp3-dev \
	libldap2-dev \
	libpam0g-dev \
	libsqlite3-dev \
	libsystemd-dev \
	systemd

# PSL: Packages needed for failed make of Vyos - JF
RUN apt-get update && apt-get install -y \
	kpartx

# PSL: Packages needed for frr - JF
# DK	libsnmp-dev removed, it  will be installed when net-snmp is installed BEFORE frr is built - order dependency
# And for building libyan2-dev https://docs.frrouting.org/projects/dev-guide/en/latest/building-frr-for-debian12.html#install-required-packages -JF
RUN apt-get update && apt-get install -y \
	chrpath \
	gawk \
	install-info \
	libcap-dev \
	libjson-c-dev \
	librtr-dev \
	libpam-dev \
	libprotobuf-c-dev \
	libpython3-dev:native \
	python3-sphinx:native \
	protobuf-c-compiler \
	python3-dev:native \
	texinfo \
	lua5.3 \
	autoconf \
	automake \
	make \
	libreadline-dev \
	gdb \
	libgrpc-dev \
	libpcre3-dev \
	libpcre2-dev \
	libgrpc++-dev \
	libsqlite3-dev \
	libzmq5 \
	libzmq3-dev \
	lsof \
	logrotate

# PSL: Packages needed for net-snmp - DK
RUN apt-get update && apt-get install -y \
	perl-xs-dev \
	default-libmysqlclient-dev

# PSL: Packages needed for debconf preseed selection of vpp - DK
RUN apt-get update && apt-get install -y \
	debconf-utils

# Packages needed for keepalived
RUN apt-get update && apt-get install -y \
    libipset-dev libnfnetlink-dev libnftnl-dev libnl-nf-3-dev libpopt-dev

# PSL: Packages needed for TI Boot Environment
RUN apt-get update && apt-get install -y \
	pigz \
	expect \
	pv \
	binfmtc \
	binfmt-support \
	debian-archive-keyring \
	bdebstrap \
	wget \
	swig \
	python3-pyelftools \
	python3-cryptography

RUN pip install --break-system-packages \
	toml-cli \
	yamllint

# PSL: Environment variables needed - JF
ENV DEBEMAIL="psleng@perle.com"
ENV EMAIL=${DEBEMAIL}

# Packages needed for nftables
RUN apt-get update && apt-get install -y \
      asciidoc-base

# Packages needed for iolan
RUN apt-get update && apt-get install -y \
      libc6-dev \
      ppp-dev \
      libnetfilter-queue-dev

# Allow password-less 'sudo' for all users in group 'sudo'
RUN sed "s/^%sudo.*/%sudo\tALL=(ALL) NOPASSWD:ALL/g" -i /etc/sudoers && \
    echo "vyos_bld\tALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    chmod a+s /usr/sbin/useradd /usr/sbin/groupadd

# Ensure all users have access to Go
RUN echo "export PATH=/opt/go/bin:\$PATH" >> /etc/skel/.bashrc

# Raise upper limit for UID when working in an Active Directory integrated
# environment. This solves the warning: vyos_bld's uid 1632000007 outside of the
# UID_MIN 1000 and UID_MAX 60000 range.
RUN sed -i 's/UID_MAX\t\t\t60000/UID_MAX\t\t\t2000000000/g' /etc/login.defs

# Cleanup
RUN rm -rf /tmp/*

# Remove cleanup script so that in-container apt-get install uses cache
RUN rm /etc/apt/apt.conf.d/clean

# Add cache once as it is needed by some builds in GitHub Actions
RUN apt-get update

# Disable mouse in vim
RUN printf "set mouse=\nset ttymouse=\n" > /etc/vim/vimrc.local

COPY entrypoint.sh /usr/local/bin/entrypoint.sh

# PSL: Extend secure_path for sudo
RUN sudo sed -i 's|Defaults\s\+secure_path=\"\(.*\)\"|Defaults secure_path=\"\1:/opt/go/bin\"|' /etc/sudoers

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
