#!/bin/bash
CWD=$(pwd)
KERNEL_SRC=linux
ROOT_DIR=$(dirname $(dirname $(dirname $(dirname ${CWD}))))
DEFS_FILE=".defs.mk"

set -e

if [ ! -f "${ROOT_DIR}/${DEFS_FILE}" ] ; then
    echo "E: DEF file (${ROOT_DIR}/${DEFS_FILE}) does not exist."
    exit 1
fi
. ${ROOT_DIR}/${DEFS_FILE}

if [ ! -d ${KERNEL_SRC} ]; then
    echo "Linux Kernel source directory does not exists, please 'git clone'"
    exit 1
fi

cd ${KERNEL_SRC}

if [ -d .git ]; then
    echo "I: Clean modified files - reset Git repo"
    git reset --hard HEAD
    git clean --force -d -x
fi

PLATFORM_DIR=${CWD}/platform/${BUILDTARG}
echo "BUILDTARG         : ${BUILDTARG}"
echo "BUILDTYPE         : ${BUILDTYPE}"
echo "PLATFORM_DIR      : ${PLATFORM_DIR}"

echo "I: Copy Kernel config (vyos_defconfig) to Kernel Source"
# PSL: See https://vyos.dev/T8134 . Use a straight config for now; no snippets
PSLIGNORE="I: PSL: ignore d86559a5c 2d0c394fee for now for $ARCH"
echo $PSLIGNORE
cp -rv ${PLATFORM_DIR}/arch/ .

if [ -d /usr/lib/ccache/ ]; then
    export PATH=/usr/lib/ccache:$PATH
fi

KERNEL_VERSION=$(make kernelversion)
KERNEL_SUFFIX=-$(awk -F "= " '/kernel_flavor/ {print $2}' ../../../../data/defaults.toml | tr -d \")

echo "I: Generate Kernel config"
ARCH=$(dpkg --print-architecture)
if [ "${ARCH}" = "arm64" ]; then
    KERNEL_CONFIG=arch/arm64/configs/vyos_defconfig
    #cp ${CWD}/config/arm64/vyos_defconfig ${KERNEL_CONFIG} # $PSLIGNORE
elif [ "${ARCH}" = "amd64" ]; then
    KERNEL_CONFIG=arch/x86/configs/vyos_defconfig
    #cp ${CWD}/config/x86/vyos_defconfig ${KERNEL_CONFIG} # $PSLIGNORE
else
    echo "E: unsupported architecture"
    exit 1
fi

# $PSLIGNORE
#for KRN_CONF_SNIPPET in $(ls ${CWD}/config/*.config)
#do
#    echo "I: adding configuration snippet ${KRN_CONF_SNIPPET}"
#    cat ${KRN_CONF_SNIPPET} >> ${KERNEL_CONFIG}
#done

echo "KERNEL_CONFIG: ${KERNEL_CONFIG}"

# VyOS requires some small Kernel Patches - apply them here
# It's easier to have them here and make use of the upstream
# repository instead of maintaining a full Kernel Fork.
# Saving time/resources is essential :-)
for PATCH_DIR in "$CWD/patches/kernel" "${PLATFORM_DIR}/${BUILDTYPE}/patches/kernel"
do
    echo "I: Processing kernel patches in $PATCH_DIR"
    for patch in $(ls ${PATCH_DIR})
    do
        echo "I: Apply Kernel patch: ${PATCH_DIR}/${patch}"
        # If this is a second run, some of the patches might fail because they
        # had already been applied earlier. Just log this and continue
        # instead of silently failing (set -e).
        patch -f -p1 < ${PATCH_DIR}/${patch} || { echo "E: patch $patch FAILED"; }
    done
done

# Change name of Signing Cert
sed -i -e "s/CN =.*/CN=VyOS Networks build time autogenerated Kernel key/" certs/default_x509.genkey

TRUSTED_KEYS_FILE=trusted_keys.pem
# start with empty key file
echo -n "" > $TRUSTED_KEYS_FILE
GIT_ROOT=$(git rev-parse --show-toplevel)
CERTS=$(find ${GIT_ROOT}/data/certificates -name "*.pem" -type f || true)
if [ ! -z "${CERTS}" ]; then
  # add known public keys to Kernel certificate chain
  for file in $CERTS; do
    cat $file >> $TRUSTED_KEYS_FILE
  done
  # Force Kernel module signing and embed public keys
  echo "CONFIG_SYSTEM_TRUSTED_KEYRING" >> $KERNEL_CONFIG
  echo "CONFIG_SYSTEM_TRUSTED_KEYS=\"$TRUSTED_KEYS_FILE\"" >> $KERNEL_CONFIG
fi

echo "I: make vyos_defconfig"
# Select Kernel configuration - currently there is only one
make vyos_defconfig

echo "I: Generate environment file containing Kernel variable"
EPHEMERAL_KEY="/tmp/ephemeral.key"
EPHEMERAL_PEM="/tmp/ephemeral.pem"
cat << EOF >${CWD}/kernel-vars
#!/bin/sh
export KERNEL_VERSION=${KERNEL_VERSION}
export KERNEL_SUFFIX=${KERNEL_SUFFIX}
export KERNEL_DIR=${CWD}/${KERNEL_SRC}
export EPHEMERAL_KEY=${EPHEMERAL_KEY}
export EPHEMERAL_CERT=${EPHEMERAL_PEM}
EOF

echo "I: Build Debian Kernel package"
touch .scmversion

(
  # Hack to get deps in place until arm64 upstream gets fixed.
  #
  # libperf expects $SRC at $DST but it is not.
  # For simplicity, we just monitor the build and make a link to it
  # when it appears.
  #
  # This should be a no-op once upstream is fixed at which point
  # all this code can be removed.
  #
  HACK='arm64 kernelbuild hack:'
  echo "I: $HACK BEGIN!"
  SRC=arch/arm64/include/generated/uapi/asm
  DST=tools/perf/libperf/arch/arm64/include/generated/uapi/asm
  echo "I: $HACK waiting for $SRC at $(date)..."
  while ! test -d $SRC; do sleep 1; done
  echo "I: $HACK $SRC appeared at $(date)"
  # Symlink it to the destination that libperf wants
  mkdir -p $(dirname $DST)
  if [ -d $DST ]; then
    echo "I: HACK $DST already exists; moving it aside"
    ls -l $DST/
    mv -f $DST $DST.old # JIC
  fi
  echo "I: $HACK symlink to $DST"
  ln -rfs $SRC $DST
  ls -l $DST/
  echo "I: HACK END at $(date)!"
) &

make bindeb-pkg BUILD_TOOLS=1 LOCALVERSION=${KERNEL_SUFFIX} KDEB_PKGVERSION=${KERNEL_VERSION}-1 -j $(getconf _NPROCESSORS_ONLN)

# Back to the old Kernel build-scripts directory
cd $CWD
EPHEMERAL_KERNEL_KEY=$(grep -E "^CONFIG_MODULE_SIG_KEY=" ${KERNEL_SRC}/$KERNEL_CONFIG | awk -F= '{print $2}' | tr -d \")
if test -f "${EPHEMERAL_KEY}"; then
    rm -f ${EPHEMERAL_KEY}
fi
if test -f "${EPHEMERAL_PEM}"; then
    rm -f ${EPHEMERAL_PEM}
fi
if test -f "${KERNEL_SRC}/${EPHEMERAL_KERNEL_KEY}"; then
    openssl rsa -in ${KERNEL_SRC}/${EPHEMERAL_KERNEL_KEY} -out ${EPHEMERAL_KEY}
    openssl x509 -in ${KERNEL_SRC}/${EPHEMERAL_KERNEL_KEY} -out ${EPHEMERAL_PEM}
fi
