#!/bin/bash -e
#
# PSL: Build NXP WiFi/Bluetooth drivers
#
echo === $0 BEGIN in $PWD

# Initialize repository URL variable
: ${REPO_URL:="https://github.com/psleng"}
: ${ROOTDIR:=$(dirname $(sudo git rev-parse --show-toplevel))}
BRANCH=lf-6.6.3_1.0.0

echo "Build/Install NXP 88Q9098/88W9098 branch $BRANCH"

# Clone the repos
for i in mwifiex imx-firmware
do
    if [ -d "$i" ]; then
        echo "=== $i already exists; pulling"
        cd $i; git pull; cd -
    else
        echo "=== Cloning $i"
        git clone $REPO_URL/$i.git -b $BRANCH
        if [ -f $i.patch ]; then
            echo "=== Applying patch $i.patch from $(realpath $i)"
            patch -d $i -p1 < $i.patch
        fi
    fi
done

# Build
echo "=== Building NXP kernel modules"
cd mwifiex/mxm_wifiex/wlan_src
make -j -C $ROOTDIR/vyos-build/scripts/package-build/linux-kernel/linux M=$PWD
cd -

#
# Set up nxp-wifi pieces as they would appear in the final filesystem
# (which has normally not been built at this point)
#

rm -rf fs
mkdir fs

# Copy to kernel modules filesystem
echo "=== Installing NXP kernel modules"
DST=fs/lib/modules/nxp
mkdir -p $DST
cp -f mwifiex/mxm_wifiex/wlan_src/*.ko $DST
cp -f wifi.sh $DST

# Copy firmware to filesystem
echo "=== Installing NXP firmware"
DST=fs/lib/firmware/nxp/
mkdir -p fs/lib/firmware/nxp
cp -f imx-firmware/nxp/FwImage_9098_PCIE/*.bin $DST
cp -f imx-firmware/nxp/wifi_mod_para.conf $DST

# Some useful rules
echo "=== Installing NXP related rules"
mkdir -p fs/etc/systemd/network/ fs/lib/udev/rules.d/
cp -f 99-default.link fs/etc/systemd/network/
cp -f 60-Perle-pcie-card-nxp9098.rules fs/lib/udev/rules.d/
cp -f 60-Perle-usb-modem.rules fs/lib/udev/rules.d/

## tar file for reference
#tar -C fs --owner 0 --group 0 -zcf fs.tar.gz .

VERS=1.0.0
ARCH=$(dpkg-architecture -q DEB_BUILD_ARCH)
PKG=nxp-wifi
echo "=== Creating debian package $PKG.deb"
rm -rf $PKG
mkdir -p $PKG/DEBIAN

# The control file
cat > $PKG/DEBIAN/control <<%
Package: $PKG
Version: $VERS
Priority: optional
Architecture: $ARCH
Maintainer: Perle Systems <psleng@perle.com>
Homepage: https://github.com/nxp-imx/mwifiex
Description: nxp wifi drivers.
 For JODY-W377 from NXP.
%

# The data
cp -pr fs/* $PKG

# Config files
(cd fs; find . -type f | grep systemd | sed 's/.//') > $PKG/DEBIAN/conffiles

# Changelog
CHANGELOG=$PKG/usr/share/doc/nxp-wifi/changelog.gz
mkdir -p $(dirname $CHANGELOG)
(cd mwifiex; git log) | gzip -9 > $CHANGELOG

# Copyright
COPYRIGHT=$PKG/usr/share/doc/nxp-wifi/copyright
cp mwifiex/SCR.txt $COPYRIGHT
echo See the file /usr/share/common-licenses/GPL for more information. >> $COPYRIGHT

# The md5sums
(cd $PKG; find . -type f | grep -v /DEBIAN | xargs md5sum) > $PKG/DEBIAN/md5sums

# Build $PKG.deb
fakeroot dpkg-deb --build $PKG

DEBPKG=${PKG}_${VERS}_${ARCH}.deb
mv -f $PKG.deb ../$DEBPKG
ls -l $(realpath ../$DEBPKG)
# lintian ../$DEBPKG
rm -rf fs $PKG

echo === $0 COMPLETE
