#!/bin/bash -e
#
# PSL: Build NXP WiFi/Bluetooth drivers
#
echo === $0 BEGIN in $PWD

# Initialize repository URL variable
: ${REPO_URL:="https://github.com/psleng"}
: ${ROOTDIR:=$(dirname $(sudo git rev-parse --show-toplevel))}
BRANCH=lf-6.6.3_1.0.0

echo "Build/Install NXP 88Q9098/88W9098 branch $BRANCH"

# Clone the repos
for i in mwifiex imx-firmware
do
    if [ -d "$i" ]; then
        echo "=== $i already exists; pulling"
        cd $i; git pull; cd -
    else
        echo "=== Cloning $i"
        git clone $REPO_URL/$i.git -b $BRANCH
        if [ -f $i.patch ]; then
            echo "=== Applying patch $i.patch from $(realpath $i)"
            patch -d $i -p1 < $i.patch
        fi
    fi
done

# Build
echo "=== Building NXP kernel modules"
cd mwifiex/mxm_wifiex/wlan_src
make -j -C $ROOTDIR/vyos-build/scripts/package-build/linux-kernel/linux M=$PWD
cd -

#
# Create a tar file containing additions to the filesystem
# (which has normally not been built at this point)
#

rm -rf fs
mkdir fs
TAR=fs.tar.gz

# Copy to kernel modules filesystem
echo "=== Installing NXP kernel modules for $TAR"
DST=fs/lib/modules/nxp
mkdir -p $DST
cp -f mwifiex/mxm_wifiex/wlan_src/*.ko $DST
cp -f wifi.sh $DST

# Copy firmware to filesystem
echo "=== Installing NXP firmware for $TAR"
DST=fs/lib/firmware/nxp/
mkdir -p fs/lib/firmware/nxp
cp -f imx-firmware/nxp/FwImage_9098_PCIE/*.bin $DST
cp -f imx-firmware/nxp/wifi_mod_para.conf $DST

# Some useful rules
echo "=== Installing NXP related rules for $TAR"
mkdir -p fs/etc/systemd/network/ fs/etc/udev/rules.d/
cp -f 99-default.link fs/etc/systemd/network/
cp -f 60-Perle-pcie-card-nxp9098.rules fs/etc/udev/rules.d/
cp -f 60-Perle-usb-modem.rules fs/etc/udev/rules.d/

tar -C fs --owner 0 --group 0 -zcf $TAR .

rm -rf fs

echo "=== Created tarfile $(realpath $TAR))"

echo === $0 COMPLETE
